spring:
  profiles: dev
  thymeleaf:
    cache: false
    enabled: false
server:
    port: 8780
---
spring:
  profiles: dev2
  application:
    name: webapi
  thymeleaf:
    cache: false
    enabled: false
server:
    port: 8783
logging:
  level:
    root: INFO
    com.taoweilai.modules: DEBUG
    com.taoweilai.common: DEBUG
management:
  security:
    enabled: false
