server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lanlandehai100/config-repo.git     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: lanlandehai100@sina.com                                         # git仓库的账号
          password: 120948@Acur                                            # git仓库的密码 
#Full authentication is required to access actuator endpoints. Consider adding Spring Security or set 'management.security.enabled' to false.
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8760/eureka/
management:
  security:
    enabled: false